### ISSUE TITLE
Problem: [/communities] Exception while invoking method 'populateCommunityRatings' ReferenceError: log is not defined

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1198]
Problem: 

When clicking "next":

```
[34mI20180417-06:10:04.137(-4)? [39mException while invoking method 'populateCommunityRatings' ReferenceError: log is not defined
[34mI20180417-06:10:04.138(-4)? [39m    at DDPCommon.MethodInvocation.populateCommunityRatings (imports/api/communities/methods.js:224:25)
[34mI20180417-06:10:04.138(-4)? [39m    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
[34mI20180417-06:10:04.138(-4)? [39m    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
[34mI20180417-06:10:04.138(-4)? [39m    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
[34mI20180417-06:10:04.139(-4)? [39m    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
[34mI20180417-06:10:04.139(-4)? [39m    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
[34mI20180417-06:10:04.139(-4)? [39m    at Promise (packages/ddp-server/livedata_server.js:715:46)
[34mI20180417-06:10:04.139(-4)? [39m    at new Promise (<anonymous>)
[34mI20180417-06:10:04.139(-4)? [39m    at Session.method (packages/ddp-server/livedata_server.js:689:23)
[34mI20180417-06:10:04.140(-4)? [39m    at packages/ddp-server/livedata_server.js:559:43
```

**Comment by anbud** [comment]
@blockrazorbot claim
