### ISSUE TITLE
Problem: DDP latency causes slow loading

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#197]
Problem: It takes a while for DDP to crank up. The DOM renders before DDP is ready, this can be confusing to users (especially on slow connections).

Solution: wherever possible, use Fast Render to send the initial DDP payload over HTTP.
Fast Render is already installed and just needs to be deployed: https://github.com/Blockrazor/blockrazor/blob/ff709fa271babb1363b7b16f6757d402ed66d21b/server/main.js#L147

**Comment by gazhayes** [comment]
@anbud if you haven't started this can you look at 273?

**Comment by anbud** [comment]
@gazhayes, not yet. Should I do anything with it?

**Comment by gazhayes** [comment]
Ok cool. This one is pretty simple and I added some things that I' 99.99% sure are much more interesting for you, so I de-assigned you.

**Comment by janat08** [comment]
I'm doing this and I can't handle imports: https://github.com/janat08/blockrazor/blob/fast-render/lib/routes.js
```
Error: Cannot find module './currencyEdit.html'
```
I moved it out of imports and into lib since routes have to be also on server side for fast render.

**Comment by AshHimself** [comment]
@janat08 - currencyEdit.html is intentionally supposed to be in the imports directory as that is the architecture we are moving towards and away from the lib directory. Are you doing your imports correctly?

**Comment by janat08** [comment]
I belief I am, if you move it into client folder it won't throw errors. I edited error message. Im trying to do the same thing on meteor todos example and it will throw errors for modules not found way down the line for the imports that I'm not even using within routes.js. Forums will just suggest running separate routes directory for fast render alone on server side.

**Comment by janat08** [comment]
```

Error: Cannot find module './loading.html'
    at makeMissingError (packages\modules-runtime.js:231:12)
    at require (packages\modules-runtime.js:241:19)
    at loading.js (imports/ui/components/loading.js:1:14)
    at fileEvaluate (packages\modules-runtime.js:343:9)
    at require (packages\modules-runtime.js:238:16)
    at app-body.js (imports/ui/layouts/app-body.js:1:1021)
    at fileEvaluate (packages\modules-runtime.js:343:9)
    at require (packages\modules-runtime.js:238:16)
    at routes.js (lib/routes.js:1:214)
    at fileEvaluate (packages\modules-runtime.js:343:9)
Exited with code: 1
```

**Comment by gazhayes** [comment]
You mean moving routes.js to /lib, NOT currencyEdit.html?

**Comment by janat08** [comment]
Yes moving routes.js to lib or import to server will just break.

**Comment by gazhayes** [comment]
Ah ok. Well that's not so bad. However @anbud and @ashhimself might have some ideas.

**Comment by janat08** [comment]
heres my reproductions which will throw errors for things breaking further down the line: https://github.com/janat08/todos

**Comment by janat08** [comment]
I also considered searching for SSR examples as they would run into similar issues or a good fast-render example repo, if you don't want to decouple fast render logic from routes config.

**Comment by gazhayes** [comment]
You can decouple FR logic from routes if you want.
