### ISSUE TITLE
Problem: adding image to hashpower causes error

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#406]
Problem: error when uploading image (wrong directory)
```
[34mI20180309-06:50:37.070(-5)? [39mException while invoking method 'uploadHashPowerImage' Error: ENOENT: no such file or directory, open '/Users/hellofriend/Documents/upload/hashpower/962ff39606a907d83f36cab046013272.jpeg'
[34mI20180309-06:50:37.071(-5)? [39m    at Object.fs.openSync (fs.js:646:18)
[34mI20180309-06:50:37.071(-5)? [39m    at Object.fs.writeFileSync (fs.js:1291:33)
[34mI20180309-06:50:37.071(-5)? [39m    at DDPCommon.MethodInvocation.uploadHashPowerImage (imports/api/hashpower/methods.js:438:12)
[34mI20180309-06:50:37.071(-5)? [39m    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
[34mI20180309-06:50:37.072(-5)? [39m    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
[34mI20180309-06:50:37.072(-5)? [39m    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
[34mI20180309-06:50:37.072(-5)? [39m    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
[34mI20180309-06:50:37.072(-5)? [39m    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
[34mI20180309-06:50:37.072(-5)? [39m    at Promise (packages/ddp-server/livedata_server.js:715:46)
[34mI20180309-06:50:37.073(-5)? [39m    at new Promise (<anonymous>)
```

Should be /var/www/static/images/hashpower

**Comment by AshHimself** [comment]
I sense a test script :/ @anbud can we assert text files for values?
