### ISSUE TITLE
Problem: #432 breaks build process

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#434]
Problem: #432 breaks Meteor
```
[34mW20180310-01:30:56.774(-5)? (STDERR) [39m[35m/home/gareth/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280[39m
[34mW20180310-01:30:56.775(-5)? (STDERR) [39m[35m						throw(ex);[39m
[34mW20180310-01:30:56.775(-5)? (STDERR) [39m[35m						^[39m
[34mW20180310-01:30:56.776(-5)? (STDERR) [39m[35m[39m
[34mW20180310-01:30:56.776(-5)? (STDERR) [39m[35mError: Cannot find module '/imports/api/coins/currencies.js'[39m
[34mW20180310-01:30:56.777(-5)? (STDERR) [39m[35m    at makeMissingError (packages/modules-runtime.js:231:12)[39m
[34mW20180310-01:30:56.777(-5)? (STDERR) [39m[35m    at require (packages/modules-runtime.js:241:19)[39m
[34mW20180310-01:30:56.777(-5)? (STDERR) [39m[35m    at indexDB.js (imports/api/indexDB.js:1:3092)[39m
[34mW20180310-01:30:56.778(-5)? (STDERR) [39m[35m    at fileEvaluate (packages/modules-runtime.js:343:9)[39m
[34mW20180310-01:30:56.778(-5)? (STDERR) [39m[35m    at require (packages/modules-runtime.js:238:16)[39m
[34mW20180310-01:30:56.778(-5)? (STDERR) [39m[35m    at main.js (server/main.js:1:181)[39m
[34mW20180310-01:30:56.779(-5)? (STDERR) [39m[35m    at fileEvaluate (packages/modules-runtime.js:343:9)[39m
[34mW20180310-01:30:56.779(-5)? (STDERR) [39m[35m    at require (packages/modules-runtime.js:238:16)[39m
[34mW20180310-01:30:56.779(-5)? (STDERR) [39m[35m    at Bounties.js (lib/database/Bounties.js:1:22)[39m
[34mW20180310-01:30:56.780(-5)? (STDERR) [39m[35m    at fileEvaluate (packages/modules-runtime.js:343:9)[39m
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by gazhayes** [comment]
https://blockrazor.org/static/log.txt

**Comment by janat08** [comment]
I can't tell why there's a problem. it's importing file that exists and is there.

**Comment by janat08** [comment]
Perhaps revert and ask anyone to look at it, because I have no idea what could possibly be wrong.

**Comment by gazhayes** [comment]
Found the problem: Currencies.js vs currencies.js

**Comment by gazhayes** [comment]
fixed in #435

**Comment by gazhayes** [comment]
@janat08 are you using Windows for your development environment? Just remember *nix has a case sensitive filesystem. That could be why it was working on your local machine but not on the production server.

**Comment by janat08** [comment]
wasn't working on my system, and I used lowercase everywhere.

**Comment by gazhayes** [comment]
Why did you send a PR if it wasn't working on your system? *always* make sure your changes do not break Meteor *before* you send a pull request.

**Comment by janat08** [comment]
I resolved conflict and it stopped working.

**Comment by gazhayes** [comment]
I left a comment on the code of the first PR (with conflicts). I'm sure it was broken then already because Currencies.js was changed to currencies.js

It's ok, and it's a very simple mistake, but just be careful in future. It's also a lesson in how something really basic and simple can make you bang your head against the wall trying to look for a complicated reason for why it's not working.
